#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "Please run as a root user or using sudo"
  exit 1
fi
# checks if script is being run with sudo or as root user. exit if not.

if [ $# -eq 0 ]; then
    echo "No options or arguments provided. You need to at least provide a username using -u"
    exit 1
fi
# checks if script is given no arguments or options 

# Sets default values if no inputs are given
user=""
shell="/bin/bash"
new_user=0
base_uid=1000
group_add=""

user_exists() { 
    if grep -q -e "^$1:" /etc/passwd; then
      # checks if the username given as a argument exists in the /etc/passwd file
        echo "That user already exists"
        exit 3 # Exit because user already exists
    fi
}

check_uid() {
  while [[ $new_user -eq 0 ]]; do
    if grep -q -e ":$base_uid:" /etc/passwd || grep -q -e ":$base_uid:" /etc/group; then
      # checks if base_uid is already used in /etc/passwd or if a group is already using the desired ID
      base_uid=$(( base_uid + 1 ))
      # if it is there, then add 1 to the uid and try again to check
    else
      base_gid=$base_uid 
      new_user=1
      # sets to 1 to exit out of the loop after
    fi
    # checks in /etc/passwd if the UID already exists in the file
    # if UID already exists, then increment UID by 1 and check again
    # if there is no matching UID, then change new_user to 1 to exit the while loop
    # source: https://man.archlinux.org/man/grep.1
  done
}

add_user() {
  home_dir="/home/$user"
  echo "$user:x:$base_uid:$base_gid:$user:$home_dir:$shell" >> /etc/passwd
  # appends the new user information into the /etc/passwd file
  # source: https://stackoverflow.com/questions/7859281/how-to-add-user-with-out-using-useradd-or-similar-command
  mkdir /home/$user
  # creates the home directory of the new user
  chown -R "$user:" "$home_dir"
  # changing ownership of the home directory to the new user created 
  cp -pr /etc/skel /home/$user
  # source: https://man.archlinux.org/man/cp.1
  # source: https://superuser.com/questions/61611/how-to-copy-with-cp-to-include-hidden-files-and-hidden-directories-and-their-con
  echo "$user:x:$base_gid:$user" >> /etc/group
  # adding the user to their default group with the same name as the username
} 

make_passwd() {
  echo "$user:$password" | chpasswd

i  # source: https://stackoverflow.com/questions/2150882/how-to-automatically-add-user-account-and-password-with-a-bash-script
  # source: https://man.archlinux.org/man/chpasswd.8
}

add_group() {

  for group in ${group_add[@]}; do 
    if ! grep -q $group /etc/group; then
      # checks that the desired group name actually exists already
      echo "This group does not exist"
      exit 3
    fi

    group_line=$(grep "^$group:" /etc/group)
    # finds the group in the /etc/group file and saves the text line to variable
    if [[ $group_line =~ :$ ]]; then
      # checks if the last character is a : using a regex to check if there are any users already in the group
      # source: https://stackoverflow.com/questions/21425006/how-to-check-if-the-last-string-character-equals-in-bash
      modified_group="${group_line}${user}"
      # adds the user to the end of the line
    else
      modified_group="${group_line},${user}"
      # adds user to the end of the line but adds a comma if a user is already in the group
      # creates a modified new line adding the new user to the group
    fi
    sed -i "s|$group_line|$modified_group|g" /etc/group
    # replaces the old text saved in $group_line with the new text saved in $modified_group
    # source: https://askubuntu.com/questions/20414/find-and-replace-text-within-a-file-using-commands
    # source: https://man.archlinux.org/man/sed.1
  done
}


while getopts ":g:s:u:" opt; do
  case "${opt}" in
    u)
      user=${OPTARG}
      # sets the user based on the user input
      ;;
    s)
      shell=/bin/${OPTARG}
      # sets the desired shell based on user unput
      ;;

    g) 
      read -a group_add <<< ${OPTARG}
      # gets a string of the group to add user to and save it to an array group_add
      ;;
    :)
      if [[ "${OPTARG}" == "u" ]]; then  
        echo "Error: -${OPTARG} requires a custom user name"
        exit 2
      elif [[ "${OPTARG}" == "s" ]]; then
        echo "Error: -${OPTARG} requires a custom shell"
        exit 2
      elif [[ "${OPTARG}" == "g" ]]; then
        echo "Error: -${OPTARG} requires at least one group to add the user to"
        exit 2
      fi
      # error for when a user puts an option but has no argument with it when it needs one
      ;;
    *)
      echo "Error: Please enter a valid option"
      exit 2

      # error for when a user give an option other than -d or -u
  esac
done

# MAIN PART OF THE CODE TO CREATE USER

if [[ -z $user ]]; then
  echo "No username was provided with -u. Please provide a username"
  exit 1
fi 

user_exists
check_uid
echo "Creating the user $user with UID $base_uid"
add_user

if [[ -n $group_add ]]; then
  add_group
  echo "Adding the new user to the specified groups"
fi

passwd $user
