#!/bin/bash

user_home=$1
# saving the argument passed into the script as a variable user_home for the user's home directory

if [[ -d "$user_home/.bashrc" ]]; then
  # checks if the .bashrc file already exists
  rm $user_home/.bashrc
  # removes the ./bashrc file if it already exists because we're going to create a new one
fi

ln -s /home/$user_home/copy_config/bin /home$user_home/bin
ln -s /home/$user_home/copy_config/config /home$user_home/.config
ln -s /home/$user_home/copy_config/home/bashrc /home$user_home/.bashrc

# creating symbolic links to the cloned configuration files from the ifiles on the PC for the new user
