#!/bin/bash

pacman -Syu

for package in "$@"; do
  pacman -S --noconfirm "$package"
done 
# loops through the packages sent into this script as a package and installs them with pacman
# pacman uses --noconfirm to bypass any messages since we're running it from a script
# source: https://man.archlinux.org/man/pacman.8
